import type { Metadata } from 'next'
import LegalPage from '../../components/LegalPage'

export const metadata: Metadata = {
  title: 'Terms of Service — Specterfy',
  description: 'Terms of service governing use of the Specterfy platform.',
}

export default function TermsPage() {
  return (
    <LegalPage
      type="terms"
      title="Terms of Service"
      subtitle="Legal"
      updated="March 19, 2026"
      intro="These Terms of Service govern your access to and use of Specterfy. By creating an account or using the service, you agree to be bound by these terms. If you do not agree, do not use the service."
      sections={[
        {
          title: 'What Specterfy Is',
          content: 'Specterfy is a privacy pre-processing utility. It is designed to help users sanitize sensitive PDF documents before those documents move into downstream handling workflows. Specterfy is not a notary journal, an e-notary platform, a RON platform, an ID verification service, or a legal compliance guarantee. Specterfy does not make legal decisions and does not replace professional judgment or legal obligations.',
        },
        {
          title: 'User Responsibility',
          content: [
            'You remain solely responsible for reviewing all outputs generated by Specterfy before downstream use.',
            'You remain responsible for ensuring your workflows comply with applicable laws and regulations.',
            'Specterfy does not guarantee that outputs meet any specific legal standard.',
            'You must not use Specterfy to process documents in ways that violate applicable law.',
            'You are responsible for maintaining the security of your account credentials.',
          ],
        },
        {
          title: 'Accounts',
          content: 'You must provide accurate account information at signup. You are responsible for activity under your account. Sharing accounts between users is not permitted. Specterfy reserves the right to suspend or terminate accounts that violate these terms.',
        },
        {
          title: 'Free Plan',
          content: 'The free plan provides 5 sanitize operations per day. Free plan access may be modified or discontinued at any time with reasonable notice.',
        },
        {
          title: 'Paid Plans',
          content: 'Paid plans are billed through Stripe. Access to paid features is contingent on confirmed payment. Specterfy reserves the right to modify pricing with reasonable advance notice. Refunds are handled on a case-by-case basis.',
        },
        {
          title: 'Prohibited Use',
          content: [
            'Attempting to reverse engineer, circumvent, or abuse usage limits.',
            'Using Specterfy to process documents in violation of applicable law.',
            'Attempting to gain unauthorized access to other user accounts or systems.',
            'Using the service to facilitate harm to third parties.',
          ],
        },
        {
          title: 'No Warranty',
          content: 'Specterfy is provided as-is without warranty of any kind, express or implied. Specterfy does not warrant that the service will be uninterrupted, error-free, or that outputs will meet any specific standard or legal requirement.',
        },
        {
          title: 'Limitation of Liability',
          content: 'To the maximum extent permitted by applicable law, Specterfy shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service. Your sole remedy for dissatisfaction with the service is to stop using it and close your account.',
        },
        {
          title: 'Changes to Terms',
          content: 'Specterfy may update these terms at any time. Continued use of the service following notice of an update constitutes acceptance of the revised terms.',
        },
        {
          title: 'Governing Law',
          content: 'These terms are governed by applicable law. Any disputes shall be resolved through appropriate legal channels.',
        },
      ]}
    />
  )
}
